config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'random_books', to: 'pages#random_books', defaults: { format: :json }
  get 'our_selection', to: 'pages#our_selection', defaults: { format: :json }
  get 'season', to: 'pages#season', defaults: { format: :json }
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  post 'start_recommendation', to: 'pages#start_recommendation'
  get 'books_for_carousel', to: 'pages#load_user_content'

  resources :books do
    resources :reviews, only: [:create]
    resources :user_libraries, only: [:create, :destroy]
    resources :read_books, only: [:destroy, :create]
  end

  resources :read_books, only: [:index, :destroy]
  resources :user_libraries, only: [:index, :destroy]
  resources :bookstores, only: [:index]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1 alert-center hideMe" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if flash[:book] %>
  <div class="alert alert-info alert-dismissible fade show m-1 alert-center hideMe" id="alert-book" role="alert">
    <%= flash[:book] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1 alert-center" role="alert" id="alert-message">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class= "footer">
  <div class="footer-container">

    <div class="footer-section about">
      <h2>About Us</h2>
      <p>Your favorite place to find books of all genres and categories. Explore our collection and enjoy reading.</p>
    </div>

    <div class="footer-section links">
      <h2>Quick Links</h2>
      <ul>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
        <li><a href="#">Reviews</a></li>
      </ul>
    </div>

    <div class="footer-section contact">
      <h2>Contact Us</h2>
      <p><i class="fas fa-map-marker-alt"></i> Booksore, London, England</p>
      <p><i class="fas fa-phone"></i> +44 62078 9075</p>
      <p><i class="fas fa-envelope"></i> info@Bookwanderer.com</p>
    </div>

    <div class="footer-section newsletter">
      <h2>Newsletter</h2>
      <form>
        <input type="email" placeholder="Enter your email" required>
        <button type="submit">Subscribe</button>
      </form>
    </div>

    <div class="footer-bottom">
      <p>&copy; 2024 BookWanderer | Follow us</p>
      <div class="socials">
        <a href="#"><i class="fab fa-facebook-f"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-linkedin-in"></i></a>
      </div>
    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>

      <%= image_tag "store-logo.png", class: "navbar-logo" %>

    <% end %>

    <div class="nav-search">
      <%= form_with url: books_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control search-input",
              placeholder: "Search books, authors, genres"
          %>
        <%= button_tag type: 'submit', class: "btn", id: "search-button" do %>
          <i class="fa-solid fa-magnifying-glass"></i>
        <% end %>
      <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Books", books_path, class: "nav-link" %>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dashboard
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="<%= user_libraries_path %>">Wishlist</a></li>
              <li><a class="dropdown-item" href="<%= read_books_path %>">Read books</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "https://png.pngtree.com/png-vector/20191101/ourmid/pngtree-cartoon-color-simple-male-avatar-png-image_1934459.jpg", class: "avatar", alt: "User Avatar" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Account", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>