config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'random_books', to: 'pages#random_books', defaults: { format: :json }
  get 'our_selection', to: 'pages#our_selection', defaults: { format: :json }
  get 'season', to: 'pages#season', defaults: { format: :json }
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  post 'start_recommendation', to: 'pages#start_recommendation'
  get 'books_for_carousel', to: 'pages#load_user_content'

  resources :books do
    resources :reviews, only: [:create]
    resources :user_libraries, only: [:create, :destroy]
    resources :read_books, only: [:destroy, :create]
  end

  resources :read_books, only: [:index, :destroy]
  resources :user_libraries, only: [:index, :destroy]
  resources :bookstores, only: [:index]
end

app/models/book.rb
class Book < ApplicationRecord
  # Associations
  has_many :read_books, dependent: :destroy
  has_many :users, through: :read_books, source: :user, as: :user_read_books
  has_many :user_libraries, dependent: :destroy
  has_many :users, through: :user_libraries, source: :user, as: :user_owned_books
  has_many :reviews, through: :read_books
  has_many :bookstore_books, dependent: :destroy
  has_many :bookstores, through: :bookstore_books
  has_many :recommendations, dependent: :destroy
  has_many :recommended_users, through: :recommendations, source: :user
  has_many :seasons, dependent: :destroy

  validates :title, :author, :genre, presence: true
  include PgSearch::Model

  pg_search_scope :search_by_title_author_and_genre,
  against: [ :title, :author, :genre, :summary ],
  using: {
    tsearch: { prefix: true }
  }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    SeasonJob.perform_later
    if params[:query].present?
      @books = Book.search_by_title_author_and_genre(params[:query])
    else
      @books = Book.all
    end
  end

  def show
    @book = Book.find(params[:id])

    # addings instances for creating bookstores markers
    @bookstores = Bookstore.all
        # The `geocoded` scope filters only flats with coordinates
        # Build the markers array
        @markers = @bookstores.map do |bookstore|
         {
          name: bookstore.name,
          address: bookstore.address,
          lat: bookstore.latitude,
          lng: bookstore.longitude,
          availability: bookstore.availability
        }
      end


    if UserLibrary.exists?(book_id: params[:id], user_id: current_user.id)
      @availability = 'library'
    elsif ReadBook.exists?(book_id: params[:id], user_id: current_user.id)
      @availability = 'read'
    else
      @availability = 'available'
    end

# || ReadBook.exists?(book_id: params[:id], user_id: current_user.id)
#
    # @availability = !UserLibrary.exists?(book_id: params[:id], user_id: current_user.id)

    # Find users who have read the current book
    # pluck is a built in ruby method that shows as more than one value - it's like distinct in SQL
    user_ids = ReadBook.where(book_id: @book.id).pluck(:user_id)

    # Find other books that these users have read (NOT includnig the current book)
    @other_books = Book.joins(:read_books)
                       .where(read_books: { user_id: user_ids })
                       .where.not(id: @book.id)
                       .distinct

    @usernames = User.where(id: user_ids)

  end
end

app/views/books/_book.html.erb
<div class="book-card">
  <% if book.cover_image_url.present? %>
    <%= link_to book_path(book) do %>
      <%= image_tag book.cover_image_url, alt: book.title, class: "book-image" %>
    <% end %>
  <% else %>
    <%= link_to book_path(book) do %>
      <%= image_tag 'https://salonlfc.com/image-not-found-2/', alt: 'No available cover', class: "book-image" %>
    <% end %>
  <% end %>
  <h5 class="book-title"><%= link_to book.title, book_path(book), style: "text-decoration: none; color: inherit"%></h5>
  <p class="book-info"><%= book.genre %> | ★★★★☆</p>
</div>

app/views/books/index.html.erb
<div class="container mt-3">
  <h1>Results</h1>
  <br>
  <div class="row scrolling-wrapper">
    <% @books.each do |book| %>
      <div class="col-lg-3 col-md-6 mb-4">
        <div class="book-card d-flex flex-column position-relative">
          <% if book.cover_image_url.present? %>
            <%= link_to book_path(book) do %>
              <%= image_tag book.cover_image_url, alt: book.title, class: "book-image" %>
            <% end %>
          <% else %>
            <%= link_to book_path(book) do %>
              <%= image_tag 'https://salonlfc.com/image-not-found-2/', alt: 'No cover available', class: "book-image" %>
            <% end %>
          <% end %>

          <h5 class="book-title">
            <%= link_to book.title, book_path(book), style: "text-decoration: none; color: inherit"%>
          </h5>
          <p class="book-info"><strong><%= book.author %></strong></p>
          <p class="book-info"><%= book.genre %> | ★★★★☆</p>

          <div class="mt-auto ms-auto button--group">
            <%= link_to user_libraries_path(book_id: book.id), method: :post, remote: true, class: 'icon-wrapper' do %>
              <i class="<%= UserLibrary.exists?(book_id: book.id, user_id: current_user.id) || ReadBook.exists?(book_id: book.id, user_id: current_user.id) ? 'fa-solid fa-bookmark' : 'fa-regular fa-bookmark' %>"></i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<div class="all">
  <!-- Left Side Container -->
  <div class="left_01" data-controller="bookstores">
    <div class="upper-container">
      <!-- Book Cover and Buttons -->
      <div class="left-upper-container">

        <%# Book Cover %>

        <div class="book-cover">
          <% if @book.cover_image_url.present? %>
            <%= image_tag(@book.cover_image_url, alt: "book-cover", style: "margin-top: 0.5rem; max-width: 100%; max-height: 100%; object-fit: contain;") %>
          <% else %>
            <p>No such file</p>
          <% end %>
        </div>

        <%# Additional Content Below Book Cover %>

        <div class="extra-content">
          <%# Check if Book already in Library %>
          <% if @availability == 'available' %>
            <%= link_to "Add to Library",
                        book_user_libraries_path(@book),
                        data: { turbo_method: :post },
                        class: "btn btn-secondary btn-sm" %>
          <% elsif @availability == 'library' %>
            <%= link_to "In Library",
                        book_user_libraries_path(@book),
                        data: { turbo_method: :delete },
                        class: "btn btn-secondary btn-sm" %>
          <% else %>
            <%= link_to "Read",
                        read_book_path(@book),
                        data: { turbo_method: :delete },
                        class: "btn btn-dark btn-sm" %>
          <% end %>

          <!-- Nearby Button -->
           <button id="nearby"
            class="btn btn-dark btn-sm"
            data-action="click->bookstores#toggle_map"
          >
            <i class="fa-solid fa-map-location-dot fa-lg"></i>
          </button>

        </div>
      </div>

      <!-- Book Details Right Container -->
      <div class="book-details ms-3 p-3 text-center">
        <h2><%= @book.title %></h2>
        <p class="text-wrap"><%= @book.summary %></p>
      </div>
    </div>


    <!-- Reviews Section -->
    <div id="reviews" class="reviews" data-review-form-target="reviews" style="margin-top: 40px;">
      <% @book.reviews.each do |review| %>
        <%= render partial: "reviews/review", locals: { review: review } %>
      <% end %>
    </div>

    <!-- Review Form -->
    <div data-controller="review-form" id="review_form" style="margin-top: 20px;">


      <% if @availability == 'read' %>
        <button data-action="click->review-form#toggle" class="btn btn-dark btn-sm button-review-toggle" style="padding: 10px 15px; font-size: 14px;">
          Add a review
        </button>
      <% else  %>
        <button data-action="click->review-form#toggle" class="button-review-toggle" data-bs-toggle="tooltip" data-bs-placement="right" title="A book must be read before adding a review!" style="padding: 10px 15px; font-size: 14px; font-weight: bold; border-radius: 5px; border: 1px solid grey; box-shadow: 0 0 16px rgba(0, 0, 0, .1); background-color: #6c757d;" disabled>
          Add a review
        </button>
      <% end %>

      <div data-review-form-target="form" class="d-none" style="margin-left: 2rem">
        <%= form_with(model: [@book, @book.reviews.new], data: { action: "turbo:submit-end->review-form#submitEnd" }) do |form| %>
          <div class="form-group" style="margin-bottom: 10px;">
            <%= form.text_area :content, rows: 4, style: "margin-top: 10px; width: 100%; padding: 10px; border-radius: 10px; border: 1px solid #ccc;" %>
          </div>
          <%= form.submit "Submit Review", class: "btn btn-dark btn-sm ", style: "padding: 10px 15px; font-size: 14px; border-radius: 20px;" %>
        <% end %>
      </div>
    </div>

    <!-- Map Container -->

    <div class="map-container" data-bookstores-target="map">

      <div style="margin-left: 1rem; width: 100%; height: 600px;"
           data-controller="map"
           data-map-markers-value= '<%= @markers.to_json %>'
           data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>

  <!-- Right Side Container -->
  <div class="right-container">
    <strong><p class="text-center m-3">Readers also enjoyed</p></strong>

    <!-- Related Books -->
    <div class="related-books">
      <% if @other_books.present? %>
        <ul class="list-group">
          <% @other_books.each do |book| %>
            <li class="list-group-item">
              <div class="related-book-item d-flex">
                <!-- Related Book Cover -->
                <div class="related-book-cover">
                  <%= image_tag(book.cover_image_url, alt: book.title, style: "width: 50px; height: 75px; object-fit: contain;") %>
                </div>

                <!-- Related Book Details -->
                <div class="related-book-details ms-2">
                  <%= link_to book.title, book_path(book), class: "fw-bold readers-liked" %>
                  <p><small>by <%= book.author %></small></p>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p class="text-center">No other books were found.</p>
      <% end %>
    </div>
  </div>
</div>